version: '3.4'

services:
  my_alpine:
    image: alpine
    tty: true
    ports:
      - "51830:51820/udp"
      - "51831:5001/tcp"
    environment:
      - DOTNET_URLS=http://192.168.6.1:5001
      - ASPNETCORE_URLS=http://192.168.6.1:5001
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./pre-wg0.conf:/etc/wireguard/pre-wg0.conf:ro
      - ./pre-setup.sh:/etc/wireguard/pre-setup.sh:rw
      - ./publish:/home/node_api_ro:ro
      - ./aspsecrets.json:/run/secrets/aspsecrets.json:ro
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: [sh, -c, "umask 077 && chmod +x /etc/wireguard/pre-setup.sh && /etc/wireguard/pre-setup.sh"]